### ISSUE TITLE
Inchi and arbitrary smiles to canonical smiles converter

### ISSUE THREAD

**Issue by xtracko** [RECETOX/metabodb#2]
Choose the proper canonical format of SMILES. Discover the functionality of OpenBabel to convert between various SMILES canonical formats and Inchi formats interchangeably.

**Comment by martenson** [comment]
@trachtok please track the resolution of the task here and then close it.

**Comment by trachtok** [comment]
OpenBabel can convert between inchi<->isomeric SMILES<->canonical SMILES and is for now our choice for these conversions.
